name: Run tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     
     - name: Instalar as deps do projeto
       uses: bahmutov/npm-install@v1
     
     - name: API Tests
       uses: cypress-io/github-action@v4
       with:
         install: false
         start: npm run cy:run:dash
         
     - name: Upload screenshots
       uses: actions/upload-artifact@v2.2.0
       if: failure()
       with:
         name: screenshots
         path: cypress/screenshots
         
     - name: Upload videos
       uses: actions/upload-artifact@v2.2.0
       if: always()
       with:
         name: videos
         path: cypress/videos
